version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  generate:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: touch testfile.txt
      - run: ls

  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run: ls

workflows:
  main:
    when:
      or:
        - equal: [ pytest-plugin, << pipeline.git.branch >> ]
    jobs:
      - generate
      - test
