on:
  schedule:
    - cron: '0 19 * * 6'

  # For Testing, remove
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      services:
        default: 'ls-community'
        type: string
        description: name of the service to execute tests for (e.g. "ls-community", "ls-pro", "ls-all", "s3,iam,ec2")
      localstack-image:
        required: false
        type: string
        default: 'localstack/localstack:latest'
        description: localstack docker image name to test against

name: Terraform Tests
jobs:

  prepare_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - id: set-matrix
        #run: echo "matrix=$(python -m terraform_pytest.get-services ${{ github.event.inputs.services || 'ls-community' }})" >> $GITHUB_OUTPUT
        # For testing purpose, remove the lines below
        run: echo "matrix=$(python -m terraform_pytest.get_services 'sqs,ecs')" >> $GITHUB_OUTPUT
        #run: echo "matrix=$(python -m terraform_pytest.get-services ${{ 'ls-all' }})" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test_service:
    needs: prepare_list
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        service_partition: ${{ fromJson(needs.prepare_list.outputs.matrix) }}
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.x'
        cache: true
        cache-dependency-path: terraform-provider-aws/go.sum

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.5'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Patch Terraform Provider
      run: |
        source .venv/bin/activate
        cd terraform-provider-aws && go mod vendor
        cd ../
        python -m terraform_pytest.main patch

    - name: Build ${{ matrix.service_partition.service }} Binary
      run: |
        source .venv/bin/activate
        python -m terraform_pytest.main build -s ${{ matrix.service_partition.service }}
        ls -la terraform-provider-aws/test-bin

    - name: Setup LocalStack
      env:
        LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
        TMP_USER: ${{ secrets.TMP_USER }}
        TMP_PW: ${{ secrets.TMP_PW }}
      run: |
        set -x
        source .venv/bin/activate
        pip install --pre localstack
        docker pull localstack/localstack-pro     # Make sure to pull the latest version of the image
        localstack login -u $TMP_USER -p $TMP_PW  # login is currently required
        LOCALSTACK_API_KEY=$LOCALSTACK_API_KEY localstack extensions init
        LOCALSTACK_API_KEY=$LOCALSTACK_API_KEY localstack extensions install "git+https://github.com/localstack/localstack-moto-test-coverage/#egg=collect-raw-metric-data-extension&subdirectory=collect-raw-metric-data-extension"

    - name: Run ${{ matrix.service_partition.service }} - ${{ matrix.service_partition.partition }} Tests
      env:
        PYTEST_PARALLEL_CONFIG: "${{ matrix.service_partition.service == 'ec2' && '-n 2' || '' }}"
        LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
        SERVICE: ${{ matrix.service_partition.service }}
      run: |
        source .venv/bin/activate
        if [[ ${{ matrix.service_partition.partition }} == "All" ]] 
        then
          python -m pytest $PYTEST_PARALLEL_CONFIG --junitxml=target/reports/pytest.xml terraform-provider-aws/internal/service/${{ matrix.service }} -s -v --ls-start --gather-metrics --ls-image ${{ github.event.inputs.localstack-image || 'localstack/localstack:latest' }}
        else
          python -m pytest $PYTEST_PARALLEL_CONFIG --junitxml=target/reports/pytest.xml $(python terraform_pytest/get-tests-for-partitions.py ${{ matrix.service_partition.service }} ${{ matrix.service_partition.partition }} ) -s -v --ls-start --gather-metrics
        fi

    - name: Archive Test Result
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-metrics
        path: target/reports

    - name: Logout LocalStack
      if: always()
      run: |
        source .venv/bin/activate
        localstack logout

    - name: Publish ${{ matrix.service }} Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: target/reports/*.xml
        check_name: ${{ matrix.service }} Terraform Test Results
